title: "Shotaro Mizuochi"
description: "42Tokyo学生 | 言語モデルと画像生成に興味あり"
url: "https://smizuoch.github.io"
baseurl: ""
# テーマをカスタムに変更
theme: minima
plugins:
  - jekyll-feed
markdown: kramdown

# ナビゲーション設定
header_pages:
  - about.md
  - projects.md
  - blog.md

# 社会的リンク
social_links:
  github: smizuoch
  twitter: ShotaroM8
  email: smizuoch@student.42tokyo.jp

# 著者情報
author:
  name: Shotaro Mizuochi